name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Check for Mermaid updates weekly
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install tree-sitter CLI
      run: npm install -g tree-sitter-cli

    - name: Run tests
      run: make test

    - name: Check Mermaid spec
      run: make check-spec

  nix-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run tests in Nix shell
      run: nix-shell --run "make test"